name: Vulnerabilities Scan Image Builder

inputs:
  image-name:
    required: true

runs:
  using: composite
  steps:
    - name: Generate a dummy MC ZIP
      shell: bash
      run: |
        #  Avoid scanning Java dependencies, as managed upstream
        zip -r files/hazelcast-management-center.zip $(mktemp -d)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ inputs.image-name }}
        load: true
