name: Vulnerabilities Scan Image Builder

inputs:
  image-name:
    required: true

env:
  # Not possible to set this as a default
  # https://github.com/orgs/community/discussions/46670
  shell: bash

runs:
  using: composite
  steps:
    - name: Generate a dummy MC ZIP to avoid scanning Java dependencies, as managed upstream
      shell: ${{ env.shell }}
      run: zip -r files/hazelcast-management-center.zip $(mktemp -d)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: ${{ inputs.image-name }}
        load: true
