name: 'find-base-image-digest-diff'
inputs:
  image:
    required: true
  base-image:
    required: true
outputs:
  changed:
    value: ${{ steps.find-digest-diff.outputs.changed }}
runs:
  using: "composite"
  steps:
    - id: find-digest-diff
      run: |
        set -e -o pipefail ${RUNNER_DEBUG:+-x}
        BASE_IMAGE_MANIFEST=$(docker manifest inspect -v "${{ inputs.base-image }}")
        IMAGE_MANIFEST=$(docker manifest inspect -v "${{ inputs.image }}")
        echo '## Base image digest diff' >> $GITHUB_STEP_SUMMARY
        echo '| Arch | ${{ inputs.base-image }} .digest | ${{ inputs.image }} .layers[0].digest |' >> $GITHUB_STEP_SUMMARY
        echo '| --- | --- | --- |' >> $GITHUB_STEP_SUMMARY
        
        for ARCH in $(echo "$IMAGE_MANIFEST" | jq -r '.[].Descriptor.platform.architecture'); do
          NEWEST_BASE_IMAGE_DIGEST=$(echo "$BASE_IMAGE_MANIFEST" | jq -r ".[].Descriptor | select(.platform.architecture==\"$ARCH\") | .digest")
          CURRENT_BASE_IMAGE_DIGEST=$(echo "$IMAGE_MANIFEST" | jq -r ".[] | select(.Descriptor.platform.architecture==\"$ARCH\") | .SchemaV2Manifest.layers[0].digest")
          echo "| $ARCH | $NEWEST_BASE_IMAGE_DIGEST | $CURRENT_BASE_IMAGE_DIGEST |" >> $GITHUB_STEP_SUMMARY
          if [ "$NEWEST_BASE_IMAGE_DIGEST" != "$CURRENT_BASE_IMAGE_DIGEST" ]; then
              CHANGED=true
          fi
        done
        echo "changed=$CHANGED" >> $GITHUB_OUTPUT
      shell: bash
