name: Get tags to push

inputs:
  ref:
    required: true
  release-version:
    required: true
outputs:
  tags:
    value: ${{ steps.get-tags-to-push.outputs.tags }}
runs:
  using: "composite"
  steps:
    - name: Calculate tags
      id: get-tags-to-push
      shell: bash
      run: |
        TAGS="${RELEASE_VERSION}"

        # e.g. v5.10.0
        LATEST_TAG=$( \
          git tag --list --sort=refname "v*" | \
          sort --version-sort | \
          grep -E -v 'v*BETA*' | \
          tail -n 1 \
        )

        if [[ "$LATEST_TAG" = "${REF}" ]]; then
          TAGS="${TAGS},latest"
          echo "Latest tag added: ${TAGS}"
          echo "PUSH_LATEST=yes" >> $GITHUB_ENV
        fi

        # e.g. v5.10
        MAJOR_MINOR_TAG=$(echo "${REF}" | cut -d'.' -f1,2)
        if [[ "${MAJOR_MINOR_TAG}" != "${REF}" ]]; then
          # e.g. v5.10.0
          LATEST_TAG_IN_MINOR_LINE=$( \
            git tag --list --sort=refname "${MAJOR_MINOR_TAG}*" | \
            sort --version-sort | \
            grep -E -v 'v*BETA*' | \
            tail -n 1 \
          )

          if [[ "$LATEST_TAG_IN_MINOR_LINE" = "${REF}" ]]; then
            # e.g. v5.10
            TAGS="${TAGS},${MAJOR_MINOR_TAG:1}"
            echo "Latest tag in minor line added: ${TAGS}"
          fi
        fi
        echo "tags=${TAGS}" >> ${GITHUB_OUTPUT}
      env:
        REF: ${{ inputs.ref }}
        RELEASE_VERSION: ${{ inputs.release-version }}

    - name: Print docker image tags
      shell: bash
      run: echo ${{ env.TAGS }}
