name: Publish latest-snapshot Docker image for Management Center

on:
  workflow_dispatch:

jobs:
  publish_latest_snapshot:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Docker repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0
        with:
          version: v0.8.2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/s390x
          build-args: |
            MC_VERSION=latest-snapshot
          tags: hazelcast/management-center:latest-snapshot
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
