name: Publish latest-snapshot Docker image for Management Center

on:
  workflow_dispatch:
    inputs:
      mcVersion:
        description: 'MC Version'
        type: string
        required: true
      mcRevision:
        description: 'MC Revision'
        type: string
        required: true

jobs:
  publish_latest_snapshot:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Docker repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.0
        with:
          version: v0.8.2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print MC version and revision
        run: |
          echo "mcVersion = ${{ inputs.mcVersion }}"
          echo "mcRevision = ${{ inputs.mcVersion }}"

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            MC_VERSION=${{ inputs.mcVersion }}
            MC_REVISION=${{ inputs.mcRevision }}
            MC_INSTALL_ZIP=hazelcast-management-center-latest-snapshot.zip
          tags: hazelcast/management-center:latest-snapshot
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
