name: Publish snapshot Docker image for Management Center

on:
  workflow_call:
    inputs:
      MC_VERSION:
        description: 'MC version'
        type: string
        required: false
        default: 'latest-snapshot'

jobs:
  publish_snapshot:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docker repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/s390x
          build-args: |
            MC_VERSION=${{ inputs.MC_VERSION }}
          tags: hazelcast/management-center:${{ inputs.MC_VERSION }}
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
