name: Rebuild maintained images

on:
  workflow_dispatch:
    inputs:
      minimal-supported-version:
        type: string
        description: 'Minimal supported version from which we should start checking images, e.g. 5.3, 5.4, 5.5. Default value is 5.3'
        required: false
  schedule:
    - cron: '0 6 * * *'

jobs:
  get-latest-patch-versions:
    runs-on: ubuntu-latest
    name: Get latest patch versions
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      MIN_VERSION: ${{ inputs.minimal-supported-version || '5.3'  }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: set-matrix
        name: Get latest patch versions
        run: |
          echo "Getting latest patch versions starting from $MIN_VERSION"
          declare -A latest
          latest_patches=$(git tag --list "v*" | sort -V | sed 's/^v//' | sed -n "/^${MIN_VERSION}.*\$/,\$p" | grep -v BETA | grep -v DEVEL | while IFS=. read -r major minor patch; do
            latest["${major}.${minor}"]="${major}.${minor}.${patch}"
          done
          printf "%s\n" "${latest[@]}" | jq -R . | jq -c -s .)
          
          echo '## Found latest patch versions' >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo "$latest_patches" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          echo "matrix={\"version\":$latest_patches}" >> $GITHUB_OUTPUT
