name: Rebuild maintained images

on:
  workflow_dispatch:
    inputs:
      minimal-supported-version:
        type: string
        description: 'Minimal supported version from which we should start checking images, e.g. 5.3, 5.4, 5.5. Default value is 5.3'
        required: false
  schedule:
    - cron: '0 6 * * *'

jobs:
  get-latest-patch-versions:
    runs-on: ubuntu-latest
    name: Get latest patch versions since
    env:
      MIN_VERSION: ${{ inputs.minimal-supported-version || '5.3'  }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/get-latest-patch-versions-using-tags
        id: get-latest-patch-versions
        with:
          since-version: ${{ env.MIN_VERSION }}

      - id: set-matrix
        run: |
          echo 'matrix={"version":${{ steps.get-latest-patch-versions.outputs.latest-patch-versions }}}' >> $GITHUB_OUTPUT

  trigger-rebuilds:
    runs-on: ubuntu-latest
    name: Rebuild ${{ matrix.version }} if base image changed
    needs: get-latest-patch-versions
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-latest-patch-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Checkout version ${{ matrix.version }}
        uses: actions/checkout@v4
        with:
          ref: v${{ matrix.version }}
          path: v${{ matrix.version }}

      - name: Get base image from Dockerfile
        id: get-base-image-from-dockerfile
        run: |
          echo "base-image=$(grep '^FROM ' v${{ matrix.version }}/Dockerfile | cut -d' ' -f2)" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/find-base-image-digest-diff
        id: base-image-diff
        with:
          image: hazelcast/management-center:${{ matrix.version }}
          base-image: ${{ steps.get-base-image-from-dockerfile.outputs.base-image }}
