name: Push Management Center RHEL image

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: 'Version of Management Center to build the image for, e.g. 5.1.1, 5.0.1'
        required: true
  workflow_call:
    inputs:
      RELEASE_VERSION:
        description: 'Version of Management Center to build the image for, e.g. 5.1.1, 5.0.1'
        required: true
        type: string

jobs:
  build:
    env:
      SCAN_REGISTRY: "quay.io"
      TIMEOUT_IN_MINS: 240
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v5

      - uses: madhead/semver-utils@latest
        id: version
        with:
          version: ${{ inputs.RELEASE_VERSION }}

      - name: Set scan registry secrets
        id: scan_registry_secrets
        run: |
          PROJECT_ID=${{ secrets[format('RHEL_PROJECT_ID_V{0}', steps.version.outputs.major)] }}
          echo "PROJECT_ID=${PROJECT_ID}" >> ${GITHUB_OUTPUT}

          echo "USERNAME=redhat-isv-containers+${PROJECT_ID}-robot" >> ${GITHUB_OUTPUT}

          PASSWORD=${{ secrets[format('SCAN_REGISTRY_PASSWORD_V{0}', steps.version.outputs.major)] }}
          echo "PASSWORD=${PASSWORD}" >> ${GITHUB_OUTPUT}

      - name: Set RHEL image as environment variable
        run: |
          echo "RHEL_IMAGE_TAG=${SCAN_REGISTRY}/redhat-isv-containers/${{ steps.scan_registry_secrets.outputs.PROJECT_ID }}:${{ inputs.RELEASE_VERSION }}" >> $GITHUB_ENV

      - name: Log in to Red Hat Scan Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.SCAN_REGISTRY }}
          username: ${{ steps.scan_registry_secrets.outputs.USERNAME }}
          password: ${{ steps.scan_registry_secrets.outputs.PASSWORD }}

      - name: Copy image to RedHat Container Registry
        run: |
          skopeo copy \
            --multi-arch all \
            docker://hazelcast/management-center:${{ inputs.RELEASE_VERSION }} \
            docker://${RHEL_IMAGE_TAG}

      - name: Install `preflight` OpenShift tool from GitHub
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          preflight: "latest"
          source: github
          skip_cache: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_INFRA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_INFRA_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            REDHAT_ROBOT,REDHAT/REDHAT_ISV_CONTAINERS_ROBOT
          parse-json-secrets: true

      - name: Run preflight scan
        run: |
          preflight check container ${RHEL_IMAGE_TAG} \
            --submit --pyxis-api-token=${REDHAT_ROBOT_RHEL_API_KEY} \
            --certification-component-id=${{ steps.scan_registry_secrets.outputs.PROJECT_ID }} \
            --docker-config ~/.docker/config.json

      - name: Check RedHat service status
        if: failure()
        uses: hazelcast/docker-actions/check-redhat-service-status@master
