name: Run end to end UI tests

on:
  workflow_dispatch:
    inputs:
      mcVersion:
        description: 'Management Center version'
        required: true

jobs:
  run_ui_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        repository: hazelcast/management-center
        ref: v${{ github.event.inputs.mcVersion }}
        token: ${{ secrets.GH_API_TOKEN }}

    - name: Run end to end UI tests
      working-directory: ui-tests
      run: mvn clean test -Dgroups=pr -Ddocker.image="hazelcast/management-center:${{ github.event.inputs.mcVersion }}"