name: Update DockerHub README

on:
  push:
    branches:
      - master

jobs:
  update-desc:
    runs-on: ubuntu-20.04
    steps:
      - name: Update DockerHub README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hazelcast/management-center
          short-description: Hazelcast Management Center Docker Image
          readme-filepath: ./README.md
